// <auto-generated />
namespace Branch.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class HereWeGoAgain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HereWeGoAgain));
        
        string IMigrationMetadata.Id
        {
            get { return "201910212018233_HereWeGoAgain"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
