// <auto-generated />
namespace Branch.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FixProId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixProId));
        
        string IMigrationMetadata.Id
        {
            get { return "201911211720479_Fix-ProId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
